src/WebApp.5.0.0/WebApp/Controllers/MRP/MrpPlanFiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telerik.Web.Mvc;
using com.Sconit.Entity.MRP.TRANS;
using com.Sconit.Service;
using com.Sconit.Utility;
using com.Sconit.Entity.Exception;
using com.Sconit.Service.MRP;
using com.Sconit.Entity.ORD;
using com.Sconit.Entity.MD;
using System.Text;
using com.Sconit.Entity.MRP.MD;
using System.Data.SqlClient;
using com.Sconit.Web.Models.SearchModels.ORD;
using System.Data;

namespace com.Sconit.Web.Controllers.MRP
{
    public class MrpPlanFiController : WebAppBaseController
    {
        //public IGenericMgr genericMgr { get; set; }
        //public IMrpMgr mrpMgr { get; set; }
        public IPlanMgr planMgr { get; set; }
        public IMrpOrderMgr mrpOrderMgr { get; set; }

        [SconitAuthorize(Permissions = "Url_Mrp_MrpPlanFi_Shift")]
        public ActionResult ShiftView()
        {
            return View();
        }

        [SconitAuthorize(Permissions = "Url_Mrp_MrpPlanFi_Shift")]
        public ActionResult Shift()
        {
            return View();
        }

        [SconitAuthorize(Permissions = "Url_Mrp_FiPlanExecutionMonitor_View")]
        public ActionResult _MrpFiExecutionMonitorReport()
        {
            return View();
        }
        [SconitAuthorize(Permissions = "Url_Mrp_MrpPlanFi_Shift")]
        public ActionResult _MrpShiftPlanList(string flow, DateTime planVersion, DateTime planDate, string shift)
        {
            ViewBag.Flow = flow;
            ViewBag.PlanDate = planDate;
            ViewBag.Shift = shift;
            //DateTime planVersion=DateTime.Now;
            //var dateIndex = Utility.DateTimeHelper.GetWeekOfYear(planDate);
            //var maxPlanversionOfWeeks = genericMgr.FindAll<MrpPlanMaster>
            //    ("from MrpPlanMaster where DateIndex =? And IsRelease = 1 And ResourceGroup = ? order by PlanVersion Desc  ",
            //    new object[] { dateIndex, CodeMaster.ResourceGroup.FI }, 0, 1);
            //var maxPlanversionOfWeek = (maxPlanversionOfWeeks ?? new List<MrpPlanMaster>()).FirstOrDefault();
            //if (maxPlanversionOfWeek != null)
            //{
            //    planVersion = maxPlanversionOfWeek.PlanVersion;
            //}
            //else
            //{
            //    SaveWarningMessage(string.Format("此日期没有对应的已释放班产计划。"));
            //    return PartialView();
            //}
            ViewBag.PlanVersion = planVersion;
            MrpPlanMaster mrpPlanMaster = this.genericMgr.FindById<MrpPlanMaster>(planVersion);
            ViewBag.IsRelease = mrpPlanMaster.IsRelease;
            string sql = @"select OrderNo from ORD_OrderMstr_4 as a where a.Type = ? and a.Flow = ? and a.Shift = ?
                           and a.EffDate=? and a.Status in ( ?,?,? ) ";
            IList<object> orderNos = this.genericMgr.FindAllWithNativeSql<object>(sql,
                new Object[] { CodeMaster.OrderType.Production, flow, shift, planDate.Date,
                                CodeMaster.OrderStatus.Create, CodeMaster.OrderStatus.Submit, CodeMaster.OrderStatus.InProcess });
            if (orderNos != null && orderNos.Count() > 0)
            {
                SaveWarningMessage(string.Format(Resources.EXT.ControllerLan.Con_PleaseCancelCorrespondingProductionOrderOfThisFlowShiftExits, flow, shift, orderNos[0]));
            }
            return PartialView();
        }

        [HttpGet]
        public string _planVersion(DateTime planDate)
        {
            DateTime planVersion = DateTime.Now;
            var dateIndex = Utility.DateTimeHelper.GetWeekOfYear(planDate);
            var maxPlanversionOfWeeks = genericMgr.FindAll<MrpPlanMaster>
                ("from MrpPlanMaster where DateIndex =? And IsRelease = 1 And ResourceGroup = ? order by PlanVersion Desc  ",
                new object[] { dateIndex, CodeMaster.ResourceGroup.FI }, 0, 1);
            var maxPlanversionOfWeek = (maxPlanversionOfWeeks ?? new List<MrpPlanMaster>()).FirstOrDefault();
            if (maxPlanversionOfWeek != null)
            {
                planVersion = maxPlanversionOfWeek.PlanVersion;
            }
            else
            {
                SaveWarningMessage(string.Format(Resources.EXT.ControllerLan.Con_TheDateLackCorrespondingAlreadyReleasedShiftPlan));
            }
            return planVersion.ToString("yyyy-MM-dd HH:mm:ss");
        }
        [GridAction(EnableCustomBinding = true)]
        public ActionResult _SelectBatchEditing(DateTime? planVersion, string flow, DateTime? planDate, string shift)
        {
            IList<MrpFiShiftPlan> planList = new List<MrpFiShiftPlan>();

            if (!string.IsNullOrEmpty(flow) && !string.IsNullOrEmpty(shift) && planVersion.HasValue && planDate.HasValue)
            {
                string hql = "from MrpFiShiftPlan where PlanVersion =? and ProductLine = ? and PlanDate =? and Shift = ? order by Sequence";
                planList = genericMgr.FindAll<MrpFiShiftPlan>(hql,
                    new object[] { planVersion.Value, flow, planDate.Value, shift });
                foreach (var plan in planList)
                {
                    var item = this.itemMgr.GetCacheItem(plan.Item);
                    plan.ItemDescription = item.Description;
                    plan.ReferenceItemCode = item.ReferenceCode;
                    plan.Uom = item.Uom;
                }
                planList = planList.OrderBy(p => p.Island).ThenBy(p => p.Machine).ToList();
            }
            return PartialView(new GridModel(planList));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [GridAction]
        [SconitAuthorize(Permissions = "Url_Mrp_MrpPlanFi_Shift")]
        public JsonResult _SaveBatchEditing([Bind(Prefix = "updated")]IEnumerable<MrpFiShiftPlan> updatedPlans)
        {
            try
            {
                if (updatedPlans != null)
                {
                    foreach (var plan in updatedPlans)
                    {
                        this.genericMgr.Update(plan);
                    }
                }
                object obj = new { };
                SaveSuccessMessage(Resources.EXT.ControllerLan.Con_SavedPlanSuccessfully);
                return Json(obj);
            }
            catch (Exception ex)
            {
                SaveErrorMessage(ex);
                return Json(null);
            }
        }

        [HttpPost]
        [SconitAuthorize(Permissions = "Url_Mrp_MrpPlanFi_Shift")]
        public ActionResult _CreateOrder(string flow, DateTime planVersion, DateTime planDate, string shift)
        {
            try
            {
                var orderMaster = mrpOrderMgr.CreateFiOrder(flow, planVersion, planDate, shift);
                SaveSuccessMessage(Resources.EXT.ControllerLan.Con_CreateProductionOrderSuccessfully);
                return Json(orderMaster.OrderNo);
            }
            catch (Exception ex)
            {
                SaveErrorMessage(ex);
            }
            return Json(null);
        }

        [SconitAuthorize(Permissions = "Url_Mrp_MrpPlanFi_ShiftView")]
        public string _GetShiftView(DateTime planVersion, string flow)
        {
            return planMgr.GetFiShiftPlanView(planVersion, flow).ToString();
        }

        [SconitAuthorize(Permissions = "Url_Mrp_MrpPlanFi_ShiftView")]
        public ActionResult _MrpPlanOverallView(DateTime planVersion, string flow)
        {
            var planList = new List<MrpFiMachinePlan>();
            string hql = "from MrpFiMachinePlan where PlanVersion =? and ProductLine =? order by Machine";



            planList = genericMgr.FindAll<MrpFiMachinePlan>(hql, new object[] { planVersion, flow })
               .Where(p => Math.Round(p.ShiftQty, 1) >= 0).ToList();
            return PartialView(planList);
        }

        #region Export ShiftView
        [SconitAuthorize(Permissions = "Url_Mrp_MrpPlanFi_ShiftView")]
        public ActionResult Export(DateTime planVersion, string flow, int Type)
        {
            var table = "";
            if (Type == 1)
            {
                table = _GetShiftView(planVersion, flow);
            }
            else
            {
                table = _MrpPlanOverallViewHtml(planVersion, flow);
            }
            string excelName = Type == 1 ? "ShiftView.xls" : "MrpPlanOverallView.xls";
            return new DownloadFileActionResult(table, excelName);
        }

        [SconitAuthorize(Permissions = "Url_Mrp_MrpPlanFi_ShiftView")]
        public string _MrpPlanOverallViewHtml(DateTime planVersion, string flow)
        {
            int tableColumnCount;
            int settledColumnCount;
            string ProcedureName = "USP_Busi_MRP_FiMachinePlan";
            SqlParameter[] sqlParams = new SqlParameter[4];
            sqlParams[0] = new SqlParameter("@Planversion", planVersion);
            sqlParams[1] = new SqlParameter("@Flow", flow);
            sqlParams[2] = new SqlParameter("@Type", "GetWebDisPlay");
            sqlParams[3] = new SqlParameter("@ParaAll", "");
            DataSet ds = genericMgr.GetDatasetByStoredProcedure(ProcedureName, sqlParams);
            //table returned from SP is a temporary table ,so colculate columns in SP.
            tableColumnCount = (int)ds.Tables[0].Rows[0][0];
            StringBuilder str = new StringBuilder("<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display\" id=\"datatable\" width=\"100%\"><thead><tr>");
            StringBuilder strHead = new StringBuilder("<tr>");
            #region Head
            //拼接固定列
            for (int i = 0; i < 4; i++)
            {
                str.Append("<th>" + (string)ds.Tables[1].Columns[i].ColumnName.ToString() + "</th>");
            }
            for (int i = 4; i < tableColumnCount; i++)
            {
                //SP return each column's length
                str.Append("<th style=\"text-align:center\"  style=\"text-align:center\" >");

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.MRP/MrpPlanFi/Demand.cshtml
@{
    Html.RenderAction("_SiteMapPath", "Common", new { MenuContent = "Url_Mrp_MrpPlanFi_Demand" });
}
<script type="text/javascript">
    function onSearch() {
        if ($('#DateIndex').val() == "") {
            $message.error('周不能为空。');
            return;
        }

        var data = {
            dateIndex: $('#DateIndex').val(),
            flow: $('#Flow').val(),
            type: $("input[type=radio][name=tabType]:checked").val()
        };
        //debugger
        $.ajax({
            type: "get",
            dataType: "html",
            url: "/MrpPlanFi/_GetDemand/",
            data: data,
            cache: false,
            success: function (data, textStatus) {
                $("#fdOrderDetail").html(data);
                $("#datatable").fixedtableheader({
                    headerrowsize: 1,
                    highlightrow: true
                });
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                DisplayTextMessages(XMLHttpRequest.responseText);
            }
        });
    }

    function DateIndex_DataBinding(e) {
        if ($('#DateType').val() != 4) {
            e.data = {
                dateType: 5
            }
        }
    }
</script>
<fieldset>
@using (Html.BeginForm("ExportFiDemand", "MrpPlanFi"))
{   
    <div class="search">
        <div class="editor-label-2">
            <label>
                @Resources.MRP.MrpExSectionPlan.MrpExSectionPlan_DateIndex
            </label>
        </div>
        <div class="editor-field-2">
            @{
           Html.RenderAction("_DateIndexComboBox", "Common", new
           {
               includeBlankOption = true,
               controlName = "DateIndex",
               dateType = (int)com.Sconit.CodeMaster.TimeUnit.Week
           });
            }
        </div>

        <div class="editor-label-2">
            <label>
                @Resources.MRP.MrpFiShiftPlan.MrpFiShiftPlan_ProductLine
            </label>
        </div>
        <div class="editor-field-2">
            @{
           Html.RenderAction("_FlowComboBox", "Common", new
           {
               controlName = "Flow",
               type = (int)com.Sconit.CodeMaster.OrderType.Production,
               resourceGroup = (int)com.Sconit.CodeMaster.ResourceGroup.FI,
               isMrp = true
           });
            }
        </div>
            <div class="editor-label-2">
            <label>
                类型               
            </label>
        </div>
        <div class="editor-field-2">
            @Html.RadioButton("tabType", 0, true)<span>模具</span><span
                style="margin: 4px"></span>
            @Html.RadioButton("tabType", 1, false)<span>物料</span>
        </div>
    </div>
    <div class="search-footer">
        @Html.Button(Resources.SYS.Global.Button_Search, "Url_Mrp_MrpPlanFi_Demand", new Dictionary<string, string>()
	    {
	        {"type", "button"},
	        {"id", "btnSearch"},
            {"needconfirm","false"},
            {"onclick","onSearch()"}
	    })
        <button type="button" id="btnExport">@Resources.SYS.Global.Button_Export</button>
    </div>
    
}
</fieldset>
<div id="fdOrderDetail">
</div>
<script type="text/javascript">

    $('#btnExport').click(function () {
        if ($('#DateIndex').val() == "") {
            $message.error('周不能为空。');
            return;
        }
        location.href = '/MrpPlanFi/ExportFiDemand/?DateIndex=' + $('#DateIndex').val()
            + '&Flow=' + $('#Flow').val()
            + '&Type=' + $("input[type=radio][name=tabType]:checked").val()
    });
</script>

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.MRP/MrpPlanFi/Shift.cshtml
@model com.Sconit.Web.Models.SearchModels.MRP.MrpPlanFiSearchModel
@{
    Html.RenderAction("_SiteMapPath", "Common", new { MenuContent = "Url_Mrp_MrpPlanFi_Shift" });
}
<script type="text/javascript">
    function FiShift_DataBinding(e) {
        if (e.value != "") {
            e.data = {
                flow: $('#Flow').val(),
                planVersion: $('#PlanVersion').val(),
                planDate: $('#PlanDate').val()
            }
        }
    }

    function MrpPlanMaster_Change(e) {
        Flow_Change(e);
    }

    function PlanDate_Change(e) {
        var data = { "planDate": $('#PlanDate').val() };
        $.ajax({
            type: "get",
            dataType: "text",
            url: "/MrpPlanFi/_planVersion/",
            data: data,
            success: function (data1, textStatus) {
                $('#PlanVersion').val(data1);
            }
        });

        Flow_Change(e);
    }

    function Flow_Change(e) {

        $('#Shift').data('tComboBox').value('');
        $('#Shift').data('tComboBox').text('');
        $("#Shift").data("tComboBox").reload();
        $("#fdOrderDetail").hide();
    }
    function FiShift_Change(e) {
        $("#fdOrderDetail").hide();
    }

    function onSearch() {
        if ($('#Flow').val() == "") {
            $message.error('路线不能为空。');
            return;
        }
        if ($('#PlanVersion').val() == "") {
            $message.error('计划版本不能为空。');
            return;
        }
        if ($('#PlanDate').val() == "") {
            $message.error('计划时间不能为空。');
            return;
        }
        if ($('#Shift').val() == "") {
            $message.error('班次不能为空。');
            return;
        }
        var data = {
            flow: $('#Flow').val(),
            planVersion: $('#PlanVersion').val(),
            planDate: $('#PlanDate').val(),
            shift: $('#Shift').val()
        };
        $.ajax({
            type: "get",
            dataType: "html",
            url: "/MrpPlanFi/_MrpShiftPlanList/",
            data: data,
            cache: false,
            success: function (data, textStatus) {
                DisplayJsonMessages(data);
                $("#fdOrderDetail").html(data);
                $("#fdOrderDetail").show();
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                DisplayTextMessages(XMLHttpRequest.responseText);
            }
        });
    }
</script>
@using (Html.BeginForm())
{
    <fieldset>
        <div class="search">
            @*<div class="search-label">
                <label>
                    @Resources.MRP.MrpFiShiftPlan.MrpFiShiftPlan_PlanVersion
                </label>
            </div>
            <div class="search-field">
                @{
                    Html.RenderAction("_MrpPlanMasterComboBox", "Common", new
                     {
                         controlName = "PlanVersion",
                         resourceGroup = (int)com.Sconit.CodeMaster.ResourceGroup.FI,
                         isRelease = true
                     });
                }
            </div>*@
            <div class="editor-label-2">
                <label>
                    @Resources.MRP.MrpFiShiftPlan.MrpFiShiftPlan_PlanDate
                </label>
            </div>
            <div class="editor-field-2">
                @(Html.Telerik().DatePicker().Format("yyyy-MM-dd").Name("PlanDate").Min(DateTime.Today)
                    .ClientEvents(events => events.OnChange("PlanDate_Change")))
                @Html.Hidden("PlanVersion", "")
            </div>
            <div class="editor-label-2">
                <label>
                    @Resources.MRP.MrpFiShiftPlan.MrpFiShiftPlan_ProductLine
                </label>
            </div>
            <div class="editor-field-2">
                @{
               Html.RenderAction("_FlowComboBox", "Common", new
               {
                   controlName = "Flow",
                   type = (int)com.Sconit.CodeMaster.OrderType.Production,
                   isChange = true,
                   isCreateOrder = false,
                   resourceGroup = (int)com.Sconit.CodeMaster.ResourceGroup.FI,
                   isMrp = true
               });
                }
                @Html.ValidationMessageFor(model => model.Flow)
            </div>
            <div class="editor-label-2">
                <label>
                    @Resources.MRP.MrpFiShiftPlan.MrpFiShiftPlan_Shift
                </label>
            </div>
            <div class="editor-field-2">
                @{
               Html.RenderAction("_FiShiftComboBox", "Common", new
               {
                   controlName = "Shift",
                   isChange = true,
               });
                }
            </div>
        </div>
        <div class="editor-footer">
            @Html.Button(Resources.SYS.Global.Button_Search, "Url_Mrp_MrpPlanFi_Shift", new Dictionary<string, string>()
	        {
	            {"type", "button"},
	            {"id", "btnSearch"},
                {"needconfirm","false"},
                {"onclick","onSearch()"},
	        })
        </div>
    </fieldset>
   
    <div id="fdOrderDetail" style="display: none;">
    </div>
}

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.MRP/MrpPlanFi/ShiftView.cshtml
@{
    Html.RenderAction("_SiteMapPath", "Common", new { MenuContent = "Url_Mrp_MrpPlanFi_ShiftView" });
}
<script type="text/javascript">
    function MrpPlanMaster_Change() {
        var combobox = $(this).data("tComboBox");
        if (combobox == undefined) {
            return;
        }
        if (combobox.selectedIndex == undefined || combobox.selectedIndex == -1) {
            combobox.value("");
            combobox.reload();
        } else {
            var Data = {
                planVersion: $('#PlanVersion').val()
            };
            $.ajax({
                type: "get",
                dataType: "text",
                url: "/MrpPlanEx/_GetWeekIndex/",
                data: Data,
                cache: false,
                success: function (data1) {
                $('#WeekRange').val(data1);
                }
            });
        }
    }
    function onSearch() {
        if ($('#Flow').val() == "") {
            $message.error('路线不能为空。');
            return;
        }
        if ($('#PlanVersion').val() == "") {
            $message.error('计划版本不能为空。');
            return;
        }
        var data = {
            flow: $('#Flow').val(),
            planVersion: $('#PlanVersion').val()
        };

        var url = "/MrpPlanFi/_GetShiftView/";
        var div = "#fdOrderDetail1";
        if ($("input[type=radio][name=tabType]:checked").val() == "0") {
            url = "/MrpPlanFi/_MrpPlanOverallViewHtml/";
            div = "#fdOrderDetail0";
        }

        $.ajax({
            type: "get",
            dataType: "html",
            url: url,
            data: data,
            cache: false,
            success: function (data, textStatus) {
                $(div).html(data);
                $(div).show();
                $("#datatable").fixedtableheader({
                    headerrowsize: 2,
                    highlightrow: true
                });
                $("#datatable1").fixedtableheader({
                    headerrowsize: 2,
                    highlightrow: true
                });
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                DisplayTextMessages(XMLHttpRequest.responseText);
            }
        });
    }

    function doClick(bl) {
        if (bl) {
            $("#fdOrderDetail1").hide();
            $("#fdOrderDetail0").show();
        }
        else {
            $("#fdOrderDetail1").show();
            $("#fdOrderDetail0").hide();
        }
    }

</script>
<fieldset>
    @using (Html.BeginForm("Export", "MrpPlanFi"))
    {
        <div class="search">
            <div class="editor-label-2">
                <label>
                    类型               
                </label>
            </div>
            <div class="editor-field-2">
                @Html.RadioButton("tabType", 0, true, new { onclick = "doClick(true)" })<span>整体</span><span
                    style="margin: 4px"></span>
                @Html.RadioButton("tabType", 1, false, new { onclick = "doClick(false)" })<span>明细</span>
            </div>
            <div class="editor-label-2">
                <label>
                </label>
            </div>
            <div class="editor-field-2">
            </div>
            <hr style="border: 100% dashed black;" />

            <div class="search-label">
                <label>
                    周
                </label>
            </div>
            <div class="search-field">
                @Html.TextBox("WeekRange","",new { disabled = "disabled" })
            </div>
            <div class="search-label">
            </div>
            <div class="search-field">
            </div>
            <div class="search-label">
                <label>
                    作业计划版本
                </label>
            </div>
            <div class="search-field">
                @{
                    Html.RenderAction("_MrpPlanMasterComboBox", "Common", new
                     {
                         controlName = "PlanVersion",
                         isRelease = true,
                         resourceGroup = (int)com.Sconit.CodeMaster.ResourceGroup.FI,
                         isChange = true
                     });
                }
            </div>

            <div class="editor-label-2">
                <label>
                    @Resources.MRP.MrpFiShiftPlan.MrpFiShiftPlan_ProductLine
                </label>
            </div>
            <div class="editor-field-2">
                @{
                    Html.RenderAction("_FlowComboBox", "Common", new
                    {
                        controlName = "Flow",
                        type = (int)com.Sconit.CodeMaster.OrderType.Production,
                        resourceGroup = (int)com.Sconit.CodeMaster.ResourceGroup.FI,
                        isMrp = true
                    });
                }
            </div>
        </div>
        <div class="editor-footer">
            @Html.Button(Resources.SYS.Global.Button_Search, "Url_Mrp_MrpPlanFi_ShiftView", new Dictionary<string, string>()
	        {
	            {"type", "button"},
	            {"id", "btnSearch"},
                {"needconfirm","false"},
                {"onclick","onSearch()"},
	        })
            <button type="button" id="btnExport">@Resources.SYS.Global.Button_Export</button>
        </div>

    }
</fieldset>

<div id="fdOrderDetail0" style="display: none;">
</div>
<div id="fdOrderDetail1" style="display: none;">
</div>
<script type="text/javascript">
    //Export
    $('#btnExport').click(function () {
        if ($('#Flow').val() == "") {
            $message.error('路线不能为空。');
            return;
        }
        if ($('#PlanVersion').val() == "") {
            $message.error('计划版本不能为空。');
            return;
        }
        location.href = '/MrpPlanFi/Export/?PlanVersion=' + $('#PlanVersion').val()
            + '&Flow=' + $('#Flow').val()
            + '&Type=' + $("input[type=radio][name=tabType]:checked").val()
    });
</script>

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.MRP/MrpPlanFi/_MrpFiExecutionMonitorReport.cshtml
@{
    Html.RenderAction("_SiteMapPath", "Common", new { MenuContent = "Url_Mrp_FiPlanExecutionMonitor_View" });
}
<script type="text/javascript">
    function MrpPlanMaster_Change() {
        var combobox = $(this).data("tComboBox");
        if (combobox == undefined) {
            return;
        }
        if (combobox.selectedIndex == undefined || combobox.selectedIndex == -1) {
            combobox.value("");
            combobox.reload();
        } else {
            var Data = {
                planVersion: $('#PlanVersion').val()
            };
            $.ajax({
                type: "get",
                dataType: "html",
                url: "/MrpPlanFi/_GetDateRange/",
                data: Data,
                cache: false,
                success: function (data) {
                    $message.success(data);
                }
            });
        }
    }
    function onSearch() {
        if ($("#PlanVersion").val() == "") {
          $message.error('版本号必填');
        return;
    }
    if ($("#StartDate").val() == "") {
        $message.error('开始时间号必填');
        return;
    }
    if ($("#EndDate").val() == "") {
        $message.error('结束时间必填');
        return;
    }
        var data = {
            ProdLine: $('#ProdLine').val(),
            PlanVersion: $('#PlanVersion').val(),
            StartDate: $('#StartDate').val(),
            EndDate: $('#EndDate').val()
        };

        $.ajax({
            type: "get",
            dataType: "text",
            url: "/MrpPlanFi/_GetExportFiPlanMonitor/",
            data: data,
            cache: false,
            success: function (data, textStatus) {
           
                var tabStrip = $("#fiExecutionMonitor");
                $(tabStrip).html(data);
                $("#datatable").fixedtableheader({
                    headerrowsize: 1,
                    highlightrow: true
                });
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                DisplayTextMessages(XMLHttpRequest.responseText);
            }
        });
    }
</script>
<fieldset>
    @using (Html.BeginForm("ExportFiPlanMonitor", "MrpPlanFi"))
    {   
        <div class="search">
            <div class="search-label">
                <label>
                    @Resources.MRP.MrpFiShiftPlan.MrpFiShiftPlan_PlanVersion
                </label>
            </div>
            <div class="search-field">
                @{
                    Html.RenderAction("_MrpPlanMasterComboBox", "Common", new
                     {
                         controlName = "PlanVersion",
                         resourceGroup = (int)com.Sconit.CodeMaster.ResourceGroup.FI,
                         isRelease = true,
                         isChange =true
                     });
                }
            </div>
            <div class="editor-label-2">
                    <label>
                    @Resources.EXT.PageLan.ProductionLine
                    </label>
            </div>
            <div class="editor-field-2">
                @{
                    Html.RenderAction("_FlowComboBox", "Common", new
                    {
                        controlName = "ProdLine",
                        resourceGroup = (int)com.Sconit.CodeMaster.ResourceGroup.FI,
                        type = (int)com.Sconit.CodeMaster.OrderType.Production,
                        isChange = false,
                        isCreateOrder = false,
                        isMrp =true
                    });
                }
            </div>
           <div class="editor-label-2">
                <label>
                    @Resources.EXT.PageLan.PlandateFrom
                </label>
            </div>
            <div class="editor-field-2">
                @(Html.Telerik().DatePicker().Format("yyyy-MM-dd").Name("StartDate")
                .Value(DateTime.Now)
                .HtmlAttributes(new { style = "margin-bottom: 1.3em;width:200px" }))
            </div>
            <div class="editor-label-2">
                <label>
                    @Resources.EXT.PageLan.To
                </label>
            </div>
            <div class="editor-field-2">
               @(Html.Telerik().DatePicker().Format("yyyy-MM-dd").Name("EndDate")
               .Value(DateTime.Now)
               .HtmlAttributes(new { style = "margin-bottom: 1.3em;width:200px" }))
            </div>
        </div>
        <div class="search-footer">
            @Html.Button(Resources.SYS.Global.Button_Search, "Url_Mrp_MrpPlanMi_PlanTrace", new Dictionary<string, string>()
	        {
	            {"type", "button"},
	            {"id", "btnSearch"},
                {"needconfirm","false"},
                {"onclick","onSearch()"},
	        })
            <button type="button" id="btnExport">@Resources.SYS.Global.Button_Export</button>
        </div>

    }
</fieldset>
<div id="fiExecutionMonitor">
</div>
<script type="text/javascript">

    $('#btnExport').click(function () {
        if ($("#PlanVersion").val() == "") {
            $message.error('版本号必填');
            return;
        }
        if ($("#StartDate").val() == "") {
            $message.error('开始时间号必填');
            return;
        }
        if ($("#EndDate").val() == "") {
            $message.error('结束时间必填');
            return;
        }
        $('form').submit();
    });
</script>