src/WebApp.5.0.0/WebApp/Controllers/INP/AuditInspectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using com.Sconit.Utility;
using Telerik.Web.Mvc;
using com.Sconit.Web.Models;
using com.Sconit.Entity.INP;
using com.Sconit.Service;
using com.Sconit.Entity;
using System.IO;
using com.Sconit.Web.Models.SearchModels.INV;
using com.Sconit.Entity.INV;
using System.Data.SqlClient;
using System.Data;
using com.Sconit.Entity.Exception;
using com.Sconit.Entity.MD;

namespace com.Sconit.Web.Controllers.INP
{
    public class AuditInspectionController : WebAppBaseController
    {
        //public IGenericMgr genericMgr { get; set; }
        public IInspectMgr inspectMgr { get; set; }
        #region  public
        public ActionResult Index()
        {
            return View();
        }

        [SconitAuthorize(Permissions = "Url_CUST_HuIdAuditInspection_View")]
        public ActionResult List(GridCommand command, LocationLotDetailSearchModel searchModel)
        {
            SearchCacheModel searchCacheModel = this.ProcessSearchModel(command, searchModel);
            if (string.IsNullOrEmpty(searchModel.Location))
            {
                SaveWarningMessage(Resources.EXT.ControllerLan.Con_LocationCanNotBeEmpty);
                return View();
            }
            if (string.IsNullOrEmpty(searchModel.LotNoFrom))
            {
                SaveWarningMessage(Resources.EXT.ControllerLan.Con_FirstBatchNumberCanNotBeEmpty);
                return View();
            }
            if (string.IsNullOrEmpty(searchModel.LotNoFrom) && !string.IsNullOrEmpty(searchModel.LotNoTo))
            {
                SaveWarningMessage(Resources.EXT.ControllerLan.Con_FirstBatchNumberBeEmptyCanNotInputSecondBatchNumber);
                return View();
            }



            if (!string.IsNullOrEmpty(searchModel.Location)&&!string.IsNullOrEmpty(searchModel.LotNoFrom))
            {
                ViewBag.Region = searchModel.Region;
                TempData["_AjaxMessage"] = "";
            }
            else
            {
                SaveWarningMessage(Resources.EXT.ControllerLan.Con_SearchConditionNeedLocationAndBatchNo);
            }

            return View();
        }

        [SconitAuthorize(Permissions = "Url_CUST_HuIdAuditInspection_View")]
        [GridAction(EnableCustomBinding = true)]
        public ActionResult _AjaxList(GridCommand command, LocationLotDetailSearchModel searchModel)
        {

            if (string.IsNullOrEmpty(searchModel.Location))
            {
                return PartialView(new GridModel(new List<LocationLotDetail>()));
            }
            if (string.IsNullOrEmpty(searchModel.LotNoFrom))
            {
                return PartialView(new GridModel(new List<LocationLotDetail>())); ;
            }
            if (string.IsNullOrEmpty(searchModel.LotNoFrom) && !string.IsNullOrEmpty(searchModel.LotNoTo))
            {
                return PartialView(new GridModel(new List<LocationLotDetail>()));
            }

            ReportSearchStatementModel reportSearchStatementModel = PrepareSearchStatement(command, searchModel);
            GridModel<LocationLotDetail> gridModel = GetAuditInspectionPageData<LocationLotDetail>(reportSearchStatementModel);
            foreach (var locationLotDetail in gridModel.Data)
            {
              locationLotDetail.ItemDescription=genericMgr.FindById<Item>(locationLotDetail.Item).Description;
            }

            return PartialView(gridModel);
        }


        #endregion

        private ReportSearchStatementModel PrepareSearchStatement(GridCommand command, LocationLotDetailSearchModel searchModel)
        {
           
            ReportSearchStatementModel reportSearchStatementModel = new ReportSearchStatementModel();
            reportSearchStatementModel.ProcedureName = "USP_Busi_GetPlusInventoryHuId";
            SqlParameter[] parameters = new SqlParameter[6];
            parameters[0] = new SqlParameter("@Location", SqlDbType.VarChar, 50);
            parameters[0].Value = searchModel.Location;

            parameters[1] = new SqlParameter("@Item", SqlDbType.VarChar, 50);
            parameters[1].Value = searchModel.Item;

            parameters[2] = new SqlParameter("@LotNoFrom", SqlDbType.VarChar, 50);
            parameters[2].Value = searchModel.LotNoFrom;

            parameters[3] = new SqlParameter("@LotNoTo", SqlDbType.VarChar,50);
            parameters[3].Value = searchModel.LotNoTo;


            parameters[4] = new SqlParameter("@IsFrozen", SqlDbType.Bit);
            parameters[4].Value = searchModel.IsFreeze;

            parameters[5] = new SqlParameter("@IsConsignment", SqlDbType.Bit);
            parameters[5].Value = searchModel.IsConsignment;
            reportSearchStatementModel.Parameters = parameters;
            return reportSearchStatementModel;
        }


        [AcceptVerbs(HttpVerbs.Post)]
        [GridAction]
        [SconitAuthorize(Permissions = "Url_CUST_HuIdAuditInspection_View")]
        public string New(string checkedIds, string Region)
        {
            IList<LocationLotDetail> viewLocationList = new List<LocationLotDetail>();

            string[] checkedIdArray = checkedIds.Split(',');
            string selectStatement = string.Empty;
            IList<object> selectPartyPara = new List<object>();
            foreach (var para in checkedIdArray)
            {
                if (selectStatement == string.Empty)
                {
                    selectStatement = "from LocationLotDetail where Id in (?";
                }
                else
                {
                    selectStatement += ",?";
                }
                selectPartyPara.Add(para);
            }
            selectStatement += ")";

            viewLocationList = genericMgr.FindAll<LocationLotDetail>(selectStatement, selectPartyPara.ToArray());

            BusinessException businessException = new BusinessException();
            try
            {
                #region orderDetailList

                IList<InspectDetail> inspectDetailList = new List<InspectDetail>();
                if (viewLocationList != null && viewLocationList.Count() > 0)
                {
                    foreach (LocationLotDetail locationlotdetail in viewLocationList)
                    {
                        InspectDetail inspectDetail = new InspectDetail();
                        Item item = this.genericMgr.FindById<Item>(locationlotdetail.Item);
                        inspectDetail.Item = locationlotdetail.Item;
                        inspectDetail.HuId = locationlotdetail.HuId;
                        inspectDetail.LotNo = locationlotdetail.LotNo;
                        inspectDetail.ItemDescription = item.Description;
                        inspectDetail.UnitCount = locationlotdetail.UnitCount;
                        inspectDetail.ReferenceItemCode = item.ReferenceCode;
                        inspectDetail.Uom = item.Uom;
                        inspectDetail.LocationFrom =locationlotdetail.Location;
                        inspectDetail.CurrentLocation = locationlotdetail.Location;
                        inspectDetail.BaseUom = item.Uom;
                        inspectDetail.UnitQty = 1;

                        inspectDetailList.Add(inspectDetail);

                    }
                }
                #endregion
                if (businessException.HasMessage)
                {
                    throw businessException;
                }
                if (inspectDetailList != null && inspectDetailList.Count == 0)
                {
                    throw new BusinessException(Resources.INP.InspectDetail.Errors_InspectDetail_Required);
                }
             

                InspectMaster inspectMaster = new InspectMaster();
                inspectMaster.Region = Region;
                inspectMaster.InspectDetails = inspectDetailList;

                inspectMaster.Type = com.Sconit.CodeMaster.InspectType.Barcode;
                inspectMaster.IsATP = false;

                inspectMgr.CreateInspectMaster(inspectMaster);
                SaveSuccessMessage(Resources.INP.InspectMaster.InspectMaster_Added);
                return inspectMaster.InspectNo;

            }
            catch (BusinessException ex)
            {
                Response.TrySkipIisCustomErrors = true;
                Response.StatusCode = 500;
                string messagesStr = "";
                IList<Message> messageList = ex.GetMessages();
                foreach (Message message in messageList)
                {
                    messagesStr +=  message.GetMessageString() ;
                }
                Response.Write(messagesStr);
                return string.Empty;
            }

        }

    }
}

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.INP/AuditInspection/Index.cshtml
@{
    ViewBag.Title = "Index";
    Html.RenderAction("_SiteMapPath", "Common", new { MenuContent = "Url_CUST_HuIdAuditInspection_View" });
}


@Html.Partial("_Search")

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.INP/AuditInspection/List.cshtml
@{
    ViewBag.Title = "List";
    Html.RenderAction("_SiteMapPath", "Common", new { MenuContent = "Url_CUST_HuIdAuditInspection_View" });
}

@Html.Partial("_Search")

@Html.Partial("_SearchResult")

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.INP/AuditInspection/_Search.cshtml
@using com.Sconit.Web.Models.SearchModels.INV
@using com.Sconit.Entity.SYS
<fieldset>
    @using (Html.BeginForm("List", "AuditInspection"))
    {   
        <div class="search">
            <div class="editor-label-2">
                @Html.LabelForModel(Resources.INV.LocationLotDetail.LocationLotDetail_Region)
            </div>
            <div class="editor-field-2">
                @{
        Html.RenderAction("_RegionComboBox", "Common", new
        {
            controlName = "Region",
            isChange = true,
            selectedValue = ViewBag.Region != null ? (string)ViewBag.Region : string.Empty
        });
                }
            </div>
            <div class="search-label">
                <label for="LocationLotDetail_Location">
                    @Resources.INV.LocationLotDetail.LocationLotDetail_Location
                </label>
            </div>
            <div class="search-field">
                @{
        Html.RenderAction("_LocationComboBox", "Common", new
        {
            controlName = "Location",
            checkRegion = true,
            selectedValue = TempData["LocationLotDetailSearchModel"] != null ? ((LocationLotDetailSearchModel)TempData["LocationLotDetailSearchModel"]).Location : string.Empty

        });
                }
            </div>
          
            <div class="search-label">
                <label for="LocationLotDetail_LotNo">
                    @Resources.INV.LocationLotDetail.LocationLotDetail_LotNoFrom
                </label>
            </div>
            <div class="search-field">
                @Html.TextBox("LotNoFrom", TempData["LocationLotDetailSearchModel"] != null ? ((LocationLotDetailSearchModel)TempData["LocationLotDetailSearchModel"]).LotNoFrom : string.Empty)
            </div>
            <div class="search-label">
                <label for="LocationLotDetail_LotNoTo">
                    @Resources.INV.LocationLotDetail.LocationLotDetail_LotNoTo
                </label>
            </div>
            <div class="search-field">
                @Html.TextBox("LotNoTo", TempData["LocationLotDetailSearchModel"] != null ? ((LocationLotDetailSearchModel)TempData["LocationLotDetailSearchModel"]).LotNoTo : string.Empty)
            </div>
              <div class="search-label">
                <label for="LocationLotDetail_Item">
                    @Resources.INV.LocationLotDetail.LocationLotDetail_Item
                </label>
            </div>
            <div class="search-field">
                @{
        Html.RenderAction("_ItemComboBox", "Common",
            new
            {
                controlName = "Item",
                selectedValue = TempData["LocationLotDetailSearchModel"] != null ? ((LocationLotDetailSearchModel)TempData["LocationLotDetailSearchModel"]).Item : string.Empty
            });
                    
                }
            </div>
             <div class="search-label"></div>
              <div class="search-field"></div>



            <div class="search-label">
                <label for="LocationLotDetail_Freezed">
                    @Resources.INV.LocationLotDetail.LocationLotDetail_IsFreeze
                </label>
            </div>
            <div class="search-field">
                @Html.CheckBox("IsFreeze", TempData["LocationLotDetailSearchModel"] != null ? ((LocationLotDetailSearchModel)TempData["LocationLotDetailSearchModel"]).IsFreeze : false)
            </div>
            <div class="search-label">
                <label for="LocationLotDetail_IsConsignment">
                    @Resources.INV.LocationLotDetail.LocationLotDetail_IsConsignment
                </label>
            </div>
            <div class="search-field">
                @Html.CheckBox("IsConsignment", TempData["LocationLotDetailSearchModel"] != null ? ((LocationLotDetailSearchModel)TempData["LocationLotDetailSearchModel"]).IsConsignment : false)
            </div>
        </div>
        <div class="search-footer">
            @Html.Hidden("isFromList", true)
            <button type="submit" id="btnSearch">
                @Resources.SYS.Global.Button_Search</button>
            <button type="button" id="btnSumitInspectionHuId" onclick="CheckedSumitInspectionHuId()"
                style="display: none">@Resources.SYS.Global.Button_AuditInspectionHuid</button>
        </div>

    }
</fieldset>
<script type="text/javascript">
    function Region_Change(e) {
        var combobox = $(this).data("tComboBox");
        if (combobox == undefined) {
            return;
        }
        if (combobox.selectedIndex == undefined || combobox.selectedIndex == -1) {
            combobox.value("");
            combobox.reload();
        }
        $('#Location').data('tComboBox').value('');
        $('#Location').data('tComboBox').text('');
        $("#Location").data("tComboBox").reload();
    }

    function Location_DataBinding(e) {
        e.data = {
            region: $("#Region").val()
        };
    }

</script>

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.INP/AuditInspection/_SearchResult.cshtml
@model IEnumerable<com.Sconit.Entity.INV.LocationLotDetail>
   <script type="text/javascript">
       $(function () {
           $("#checkAll").click(function () {
               $('input[name="checkedRecords"]').attr("checked", this.checked);
               $("#btnSumitInspectionHuId").attr("style", this.checked ? "display:inline" : "display:none");
           });
       });
       function showButtons() {
           var $checkRecords = $("input[name='checkedRecords']");
           var showButton = false;
           for (var i = 0; i < $checkRecords.length; i++) {
               if ($checkRecords[i].checked) {
                   showButton = true;
                   break;
               }
           }
           $("#checkAll").attr("checked", $checkRecords.length == $("input[name='checkedRecords']:checked").length ? true : false);
           $("#btnSumitInspectionHuId").attr("style", showButton ? "display:inline" : "display:none");
       }
</script>
<fieldset>
    <legend>@Resources.ORD.OrderMaster.OrderMaster_Ship_Title</legend>
    @(
        Html.Telerik().Grid(Model)
          .Name("OrderMasterGrid")
          .DataKeys(keys =>
          {
              keys.Add(p => p.Id);
          })
          .Columns(columns =>
          {
              columns.Bound(o=> o.CheckOrderNo)
                .ClientTemplate("<input type='checkbox' id='checkedRecords' name='checkedRecords' value='<#= Id #>'   onClick='showButtons()' />")
                .HeaderTemplate("<input type='checkbox' id='checkAll' name='checkAll' />")
                .Width(36).HtmlAttributes(new { style = "text-align:center" });

              columns.Bound(o => o.HuId);
              columns.Bound(o => o.HuQty);
              columns.Bound(o => o.Location);
              columns.Bound(o => o.Item);
              columns.Bound(o => o.ItemDescription);
              columns.Bound(o => o.UnitCount);
              columns.Bound(o => o.LotNo);
              columns.Bound(o => o.IsFreeze).ClientTemplate("<input type='checkbox' disabled='disabled' name='IsFreeze' <#= IsFreeze? checked='checked' : '' #> />"); ; ;
              columns.Bound(o => o.IsConsignment).ClientTemplate("<input type='checkbox' disabled='disabled' name='IsConsignment' <#= IsConsignment? checked='checked' : '' #> />"); ;
             
              columns.Bound(o => o.CreateDate);
          })
                   .CellAction(cell =>
                   {
                       if (cell.Column.Member == "CheckOrderNo")
                       {
                           cell.Text = string.Format("<input type='checkbox' id='checkedRecords' name='checkedRecords' value='{0}'  />", cell.DataItem.Id);
                       }
                   })
          .Scrollable(c => c.Enabled(false))
        .EnableCustomBinding(true)
        .DataBinding(dataBinding => dataBinding.Ajax().Select("_AjaxList", "AuditInspection"))
        .ClientEvents(events => events.OnDataBinding("LocationDetailGrid_OnDataBinding"))
        .Sortable()
        .Resizable(resizing => resizing.Columns(true))
    )
</fieldset>
 @Html.Hidden("Region_Value", (string)ViewBag.Region)
<script type="text/javascript">

    function CheckedSumitInspectionHuId() {
        var $checkRecords = $("input[name='checkedRecords']");
        var checkedIds = "";
        for (var i = 0; i < $checkRecords.length; i++) {
            if ($checkRecords[i].checked) {
                if (checkedIds == "") {
                    checkedIds =$checkRecords[i].value;
                } else {
                    checkedIds += "," + $checkRecords[i].value;
                }
            }
        }
        if (checkedIds == "") {
            alert('Must Check One');
            return;
        }

        var data = {
            "checkedIds": checkedIds,
            "Region": $('#Region_Value').val()
        };
        $.ajax({
            type: "post",
            dataType: "text",
            data: data,
            url: "/AuditInspection/New/",
            cache: false,
            success: function (data, textStatus) {
                if (data != "") {
                    $.ajax({
                        type: "post",
                        dataType: "html",
                        data: { id: data },
                        url: "/InspectionOrder/Edit/",
                        cache: false,
                        success: function (data, textStatus) {
                            var $tGrid = $("#content");
                            $($tGrid).html(data);
                        }
                    });
                }
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                var errorMessages = XMLHttpRequest.responseText;
                
                $message.error(errorMessages);
            }
        });

    }

    function LocationDetailGrid_OnDataBinding(e) {
        e.data = {
            Location: $('#Location').val(),
            Item: $('#Item').val(),
            LotNoFrom: $('#LotNoFrom').val(),
            LotNoTo: $('#LotNoTo').val(),
            IsFreeze: $("input[type=checkbox][name=IsFreeze]:checked").val(),
            IsConsignment: $("input[type=checkbox][name=IsConsignment]:checked").val()
        };
    } 

</script>