src/WebApp.5.0.0/WebApp/Controllers/ACC/UserFavoriteController.cs
/// <summary>
/// Summary description for AddressController
/// </summary>
namespace com.Sconit.Web.Controllers.ACC
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.Routing;
    using System.Web.Security;
    using com.Sconit.Entity.ACC;
    using com.Sconit.Entity.SYS;
    using com.Sconit.Service;
    using com.Sconit.Web.Models;
    using com.Sconit.Utility;
    using Telerik.Web.Mvc;
    using System.Text.RegularExpressions;
    using com.Sconit.Entity.Exception;
    using System;

    /// <summary>
    /// This controller response to control the UserFavorite.
    /// </summary>
    public class UserFavoriteController : WebAppBaseController
    {
        #region Properties
        /// <summary>
        /// Gets or sets the this.GeneMgr which main consider the UserFavorite security 
        /// </summary>
        //public IGenericMgr genericMgr { get; set; }
        #endregion

        /// <summary>
        /// Index action for UserFavorite controller
        /// </summary>
        /// <returns>rediret view</returns>
        [SconitAuthorize(Permissions = "Url_UserFav_View")]
        public ActionResult Index()
        {
            int? id = CurrentUser.Id;
            if (!id.HasValue)
            {
                return HttpNotFound();
            }
            else
            {
                User user = this.CurrentUser;
                user.NewPassword = user.Password;
                user.ConfirmPassword = user.Password;
                return View(user);
            }
        }

        /// <summary>
        /// Edit action
        /// </summary>
        /// <param name="user">user model</param>
        /// <returns>return to the result view</returns>
        [HttpPost]
        [SconitAuthorize(Permissions = "Url_UserFav_Edit")]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                user.LastPasswordModifyDate = genericMgr.FindById<User>(user.Id).LastPasswordModifyDate;
                this.genericMgr.Update(user);
                SaveSuccessMessage(Resources.ACC.User.User_Updated);
            }

            return new RedirectToRouteResult(new RouteValueDictionary  
                                                   { 
                                                       { "action", "Index" }, 
                                                       { "controller", "UserFavorite" },
                                                       { "id", user.Id }
                                                   });
        }

        /// <summary>
        /// ChangePassword action 
        /// </summary>
        /// <returns>rediret view</returns>
        [SconitAuthorize(Permissions = "Url_UserFav_Edit")]
        public ActionResult ChangePassword()
        {
            return View();
        }

        /// <summary>
        /// ChangePassword action
        /// </summary>
        /// <param name="model">Change Password Model</param>
        /// <returns>return to the result view</returns>
        [HttpPost]
        [SconitAuthorize(Permissions = "Url_UserFav_Edit")]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                Regex r = new Regex("^(?:(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])|(?=.*[A-Z])(?=.*[a-z])(?=.*[^A-Za-z0-9])|(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9])|(?=.*[a-z])(?=.*[0-9])(?=.*[^A-Za-z0-9])).{6,}|(?:(?=.*[A-Z])(?=.*[a-z])|(?=.*[A-Z])(?=.*[0-9])|(?=.*[A-Z])(?=.*[^A-Za-z0-9])|(?=.*[a-z])(?=.*[0-9])|(?=.*[a-z])(?=.*[^A-Za-z0-9])|(?=.*[0-9])(?=.*[^A-Za-z0-9])|).{8,}");

                if (!r.IsMatch(model.ConfirmPassword))
                {
                    BusinessException ex = new BusinessException();
                    ex.AddMessage(Resources.ACC.User.User_Regex);
                    SaveBusinessExceptionMessage(ex);
                }
                else
                {
                    CurrentUser.Password = FormsAuthentication.HashPasswordForStoringInConfigFile(model.ConfirmPassword, "MD5");
                    this.genericMgr.Update(CurrentUser);
                    SaveSuccessMessage(Resources.ACC.User.User_PasswordChanged);
                }
            }

            return View(model);
        }
    }
}

src/WebApp.5.0.0/WebApp/Controllers/CommonController.cs
namespace com.Sconit.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.UI.WebControls;
    using AutoMapper;
    using com.Sconit.Entity;
    using com.Sconit.Entity.ACC;
    using com.Sconit.Entity.BIL;
    using com.Sconit.Entity.CUST;
    using com.Sconit.Entity.INP;
    using com.Sconit.Entity.INV;
    using com.Sconit.Entity.ISS;
    using com.Sconit.Entity.MD;
    using com.Sconit.Entity.MRP.MD;
    using com.Sconit.Entity.MRP.ORD;
    using com.Sconit.Entity.ORD;
    using com.Sconit.Entity.PRD;
    using com.Sconit.Entity.SCM;
    using com.Sconit.Entity.SYS;
    using com.Sconit.Service;
    using com.Sconit.Web.Models;
    using NHibernate;
    using NHibernate.Criterion;
    using NHibernate.Type;
    using Telerik.Web.Mvc.UI;
    using com.Sconit.Entity.MRP.TRANS;
    using System.Text;
    using com.Sconit.CodeMaster;
    using com.Sconit.Utility;
    using System.Data;
    using System.Data.SqlClient;
    using System.Collections;
    using com.Sconit.Entity.SI.SAP;
    using com.Sconit.Entity.ISI;
    using com.Sconit.Entity.TMS;
    using com.Sconit.Entity.WMS;
    using com.Sconit.Entity.FMS;
    public class CommonController : WebAppBaseController
    {
        #region
        //下拉框默认只选出20条
        private static int firstRow = 0;
        private static int maxRow = 100;

        private static string selectEqMachineStatement = "from Machine as m where m.Code = ? ";

        private static string selectLikeMachineStatement = "from Machine as m where m.Code like ? ";

        private static string selectEqIslandStatement = "from Island as i where i.Code = ? ";

        private static string selectLikeIslandStatement = "from Island as i where i.Code like ? ";

        private static string selectEqItemStatement = "from Item as i where i.Code = ? and IsActive = ?";

        private static string selectLikeItemStatement = "from Item as i where i.Code like ? and IsActive = ?";

        private static string selectEqUserStatement = "from User as u where u.Code = ? and u.IsActive = ?";

        private static string selectLikeUserStatement = "from User as u where u.Code like ? and u.IsActive = ?";

        private static string selectEqWmsUserStatement = "from User as u where u.Id = ? and u.IsActive = ?";

        private static string selectLikeWmsUserStatement = "from User as u where u.Code like ? and u.IsActive = ?";

        private static string selectEqItemPackageStatement = "from ItemPackage as i where  convert(VARCHAR,i.UnitCount) = ?";

        private static string selectLikeItemPackageStatement = "from ItemPackage as i where i.Item=? and convert(VARCHAR,i.UnitCount) like ? ";

        private static string selectEqSupplierStatement = "from Supplier as s where s.Code = ?";

        private static string selectEqCustomerStatement = "from Customer as c where c.Code = ?";

        private static string selectEqRegionStatement = "from Region as r where r.Code = ?";

        private static string selectEqCarrierStatement = "from Carrier as c where c.Code = ?";

        private static string selectLikeRoutingStatement = "from RoutingMaster as r where r.Code like ? and IsActive = ?";

        private static string selectEqBomStatement = "from BomMaster as b where b.Code = ? and IsActive = ?";

        private static string selectSAPLocationStatement = "  select distinct top " + maxRow + "  SAPLocation from md_location  where SAPLocation = '{0}'";

        private static string selectLikeSAPLocationStatement = " select distinct top " + maxRow + "  SAPLocation from md_location  where SAPLocation like '%{0}%' ";

        private static string selectEqIssueAddressStatement = "from IssueAddress as ia where  ia.Code = ? or ia.Description = ? order by Sequence";

        private static string selectLikeIssueAddressStatement = "from IssueAddress as ia where  ia.Code like ? or ia.Description like ?  order by Sequence";

        private static string selectEqFlowStatement = "from FlowMaster as f where f.Code = ? and f.IsActive = ? ";

        private static string selectEqLocationStatement = "from Location as l where l.Code = ?";

        private static string selectEqAddressStatement = "from Address as l where l.Code = ?";

        private static string selectEqPickStrategyStatement = " from PickStrategy as w where w.Code= ? ";

        private static string selectEqTaskSubTypeStatement = "from TaskSubType as t where t.Code = ?";

        private static string selectEqTaskAddressStatement = "from TaskAddress as t where t.Code = ?";

        private static string selectEqPickGroupStatement = "from PickGroup as p where p.PickGroupCode = ? and p.Type = ?";

        private static string selectLikePickGroupStatement = "from PickGroup as p where p.PickGroupCode like ? and p.Type = ?";

        private static string selectEqPickUserStatement = "from PickUser as p where p.PickUserName = ? and p.PickGroupCode = ?";

        private static string selectLikePickUserStatement = "from PickUser as p where p.PickGroupCode = ? and p.PickUserName like ?";

        private static string selectEqShiftMasterStatement = "from ShiftMaster as s where s.Code = ?";

        private static string selectLikeShiftMasterStatement = "from ShiftMaster as s where s.Code like ? ";

        #endregion

        //public IGenericMgr genericMgr { get; set; }
        //public IItemMgr itemMgr { get; set; }

        #region public methods
        public ActionResult _SiteMapPath(string menuContent)
        {
            //IList<com.Sconit.Entity.SYS.Menu> allMenu = systemMgr.GetAllMenu();
            //IList<MenuModel> allMenuModel = Mapper.Map<IList<com.Sconit.Entity.SYS.Menu>, IList<MenuModel>>(allMenu);

            //List<MenuModel> menuList = allMenuModel.Where(m => m.Code == menuContent).ToList();
            //this.NestGetParentMenu(menuList, menuList, allMenuModel);

            //foreach (var menu in menuList)
            //{
            //    string name = Resources.SYS.Menu.ResourceManager.GetString(menu.Name);
            //    if (name != null)
            //    {
            //        menu.Name = name;
            //    }
            //}
            //return PartialView(menuList);
            return PartialView();
        }

        #region MoveType

        public ActionResult _MoveTypeDropDownList(string controlName, string controlId, string selectedValue, bool? includeBlankOption, string blankOptionDescription, string blankOptionValue, bool? coupled, string IOType, bool? isChange, string SubType, bool? enable, bool? isInitInventory)
        {
            ViewBag.ControlName = controlName;
            ViewBag.ControlId = controlId;
            ViewBag.Coupled = coupled;
            ViewBag.SelectedValue = selectedValue;
            ViewBag.IsChange = isChange;
            ViewBag.Enable = enable;
            List<Object> objs = new List<Object>();
            string hql = "from MiscOrderMoveType as m where 1=1  ";
            if (!string.IsNullOrWhiteSpace(SubType))
            {
                hql += " and m.SubType =? ";
                objs.Add(SubType);
            }
            if (!string.IsNullOrWhiteSpace(IOType))
            {
                hql += " and m.IOType=? ";
                objs.Add(IOType);
            }

            if (isInitInventory != null)
            {
                if (isInitInventory.Value)
                {
                    hql += " and m.MoveType=? ";
                    objs.Add(0);
                }
                else
                {
                    hql += " and m.MoveType != ? ";
                    objs.Add(0);
                }

            }


            IList<MiscOrderMoveType> MoveTypeList = queryMgr.FindAll<MiscOrderMoveType>(hql, objs.ToArray());
            if (MoveTypeList == null)
            {
                MoveTypeList = new List<MiscOrderMoveType>();
            }

            if (includeBlankOption.HasValue && includeBlankOption.Value)
            {
                MiscOrderMoveType blankMoveType = new MiscOrderMoveType();

                blankMoveType.Description = blankOptionDescription;
                MoveTypeList.Insert(0, blankMoveType);
            }

            return PartialView(new SelectList(MoveTypeList, "MoveType", "Description", selectedValue));

        }
        #endregion

        #region CodeMaster
        public ActionResult _CodeMasterDropDownList(com.Sconit.CodeMaster.CodeMaster code, string controlName, string controlId, string selectedValue, string ajaxActionName, bool? isSupplier,
             bool? includeBlankOption, string blankOptionDescription, string blankOptionValue, bool? enable, bool? isConsignment, bool? isShowNA, int? orderType, bool? isWidth)
        {
            IList<CodeDetail> codeDetailList = systemMgr.GetCodeDetails(code, includeBlankOption, blankOptionDescription, blankOptionValue);
            if (controlName == "ExcelTemplate")
            {
                string defaultpara = code.ToString();
                //DataSet ds = genericMgr.GetDatasetBySql(@"select distinct code from sys_codedet where value like '%xls'", null);
                //List<string> MultiCode = new List<string>();
                //foreach (DataRow dr in ds.Tables[0].Rows)
                //{
                //    MultiCode.Add(dr.ItemArray[0].ToString());
                //}

                var multiCodes = this.genericMgr.FindAllWithNativeSql<string>("select distinct code from sys_codedet where value like '%xls'");

                IList<CodeDetail> MulticodeDetailList = systemMgr.GetMultiCodeDetails(multiCodes, includeBlankOption, blankOptionDescription, blankOptionValue);
                codeDetailList = MulticodeDetailList;
            }
            if (isSupplier != null && isSupplier.Value)
            {
                codeDetailList = codeDetailList.Where(q => q.Value != ((int)com.Sconit.CodeMaster.OrderStatus.Create).ToString()).ToList();

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.ACC/UserFavorite/ChangePassword.cshtml
@model com.Sconit.Web.Models.ChangePasswordModel
@{
    Html.RenderAction("_SiteMapPath", "Common", new { MenuContent = "Url_UserFav_View" });
}
@using (Html.BeginForm())
{
    <fieldset>
    <legend>@Resources.ACC.User.User_ChangePassword_Title</legend>
    <div class="editor-label-2">
        @Html.LabelFor(model => model.NewPassword)
    </div>
    <div class="editor-field-2">
        @Html.EditorFor(model => model.NewPassword)
        @Html.ValidationMessageFor(model => model.NewPassword)
    </div>
    <div class="editor-label-2">
        @Html.LabelFor(model => model.ConfirmPassword)
    </div>
    <div class="editor-field-2">
        @Html.EditorFor(model => model.ConfirmPassword)
        @Html.ValidationMessageFor(model => model.ConfirmPassword)
    </div>
    <div class="editor-footer">
        <button type="submit" id="btnSave">
            @Resources.SYS.Global.Button_Save</button>
             <button type="button" id="btnBack" onclick="location.href='@Url.Content("~/UserFavorite/Index")'">
                @Resources.SYS.Global.Button_Back</button>
    </div>
    </fieldset>
}

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.ACC/UserFavorite/Edit.cshtml
@using com.Sconit.Entity.SYS
@model com.Sconit.Entity.ACC.User
<style>
.editor-label-2, .search-label {
    float: left;
    width: 15%;
    text-align: right;
    height: 25px;
}

.editor-field-2, .search-field {
    float: left;
    width: 35%;
    height: 25px;
}

.editor-label-2 label, .search-label label {
    padding: 0 10px 0 0;
}
</style>
@using (Html.BeginForm("Edit", "UserFavorite"))
{
    <fieldset>
        <legend>@Resources.ACC.User.User_Edit_Title</legend>
        <div class="editor">
            <div class="editor-label-2">
                @Html.LabelFor(model => model.Code)
            </div>
            <div class="editor-field-2">
                @Html.DisplayFor(model => model.Code)
                @Html.ValidationMessageFor(model => model.Code)
            </div>
            <div class="editor-label-2">
            </div>
            <div class="editor-field-2">
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.Code)
                @Html.HiddenFor(model => model.Password)
                @Html.HiddenFor(model => model.NewPassword)
                @Html.HiddenFor(model => model.ConfirmPassword)
                @Html.HiddenFor(model => model.CreateUserName)
                @Html.HiddenFor(model => model.CreateDate)
                @Html.HiddenFor(model => model.LastModifyUserName)
                @Html.HiddenFor(model => model.LastModifyDate)
                @Html.HiddenFor(model => model.IsActive)
                @Html.HiddenFor(model => model.AccountExpired)
                @Html.HiddenFor(model => model.PasswordExpired)
                @Html.HiddenFor(model => model.AccountLocked)
                @Html.HiddenFor(model => model.DomainUser)
                @Html.HiddenFor(model => model.IsActive)
                @*@Html.HiddenFor(model => model.Language)*@
                @Html.HiddenFor(model => model.IpAddress)
                @Html.HiddenFor(model => model.LastAccessDate)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.FirstName)
            </div>
            <div class="editor-field-2">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.LastName)
            </div>
            <div class="editor-field-2">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.Depart)
            </div>
            <div class="editor-field-2">
                @Html.EditorFor(model => model.Depart)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.Position)
            </div>
            <div class="editor-field-2">
                @Html.EditorFor(model => model.Position)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.Email)
            </div>
            <div class="editor-field-2">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.TelPhone)
            </div>
            <div class="editor-field-2">
                @Html.EditorFor(model => model.TelPhone)
                @Html.ValidationMessageFor(model => model.TelPhone)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.MobilePhone)
            </div>
            <div class="editor-field-2">
                @Html.EditorFor(model => model.MobilePhone)
                @Html.ValidationMessageFor(model => model.MobilePhone)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.LastPasswordModifyDate)
            </div>
            <div class="editor-field-2">
                @Html.DisplayFor(model => model.LastPasswordModifyDate)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.Language)
            </div>
            <div class="editor-field-2">
                @{
                    Html.RenderAction("_CodeMasterDropDownList", "Common", new
                    {
                        code = com.Sconit.CodeMaster.CodeMaster.Language,
                        controlName = "Language",
                        selectedValue = Model.Language,
                    });
                }
            </div>
            <div class="editor-label-2">
            </div>
            <div class="editor-field-2">
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.LastLoginDate)
            </div>
            <div class="editor-field-2">
                @Html.DisplayFor(model => model.LastLoginDate)
            </div>
            <div class="editor-label-2">
                @Html.LabelFor(model => model.LastIpAddress)
            </div>
            <div class="editor-field-2">
                @Html.DisplayFor(model => model.LastIpAddress)
            </div>
            
            @*<div class="editor-label-2">
                @Html.LabelFor(model => model.Language)
            </div>
            <div class="editor-field-2">
                @{
    Html.RenderAction("_CodeMasterDropDownList", "Common", new
    {
        code = com.Sconit.CodeMaster.CodeMaster.Language,
        controlName = "Language",
        selectedValue = Model.Language,
    });
                }
                @Html.ValidationMessageFor(model => model.Language)
            </div>*@
        </div>
        <div class="editor-footer">
            <button type="submit" id="btnSave">
                @Resources.SYS.Global.Button_Save</button>
            <button type="button" id="btnChangePassword" onclick="location.href='@Url.Content("~/UserFavorite/ChangePassword")'">
                @Resources.SYS.Global.Button_ChangePassword</button>

        </div>
    </fieldset>    
}

<script type="text/javascript">
    function a() {

        parent.Nav.ExpandNode("Url_EntityPreference_View");

    }
</script>

src/WebApp.5.0.0/WebApp/Views/com.Sconit.Web.Controllers.ACC/UserFavorite/Index.cshtml
@{
    ViewBag.Title = "Index";
    Html.RenderAction("_SiteMapPath", "Common", new { MenuContent = "Url_UserFav_View" });
}


@Html.Partial("Edit")